version: "3:8"
services:
  mongodb:
    image: mongo:5.0.6-focal
    container_name: mongo
    volumes:
      - ./docker-volumes/database/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-database

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      -  mongodb
    container_name: mongoui
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    ports:
      - "8080:8081"
    networks:
      - mongo-database

  minio:
    image: minio/minio
    volumes:
      - ./docker-volumes/minio-data:/data
    command: server /data
    environment:
      MINIO_ROOT_USER: 'minioadmin'
      MINIO_ROOT_PASSWORD: 'minioadmin'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    ports:
      - "9000:9000"
      - "9001:9001"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/short-links;
      /usr/bin/mc policy set public myminio/short-links;
      exit 0;
      "
networks:
  mongo-database:
    driver: bridge